spring:
  datasource:
    url: jdbc:mysql://hackathon-db.cdiqods6ylll.us-east-1.rds.amazonaws.com/st_hackathon
    username: admin
    password: hackathon
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 30000