spring:
  datasource:
    url: jdbc:mysql://localhost:3306/st_hackathon
    username: root
    password: admin
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 30000

  jpa:
    hibernate:
      ddl-auto: 'update'
    show-sql: true